# Generated by Django 2.0.7 on 2019-04-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pneumonic', models.CharField(max_length=5)),
                ('course_id', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('course_description', models.TextField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobView.CourseDescription')),
            ],
        ),
    ]
