# Generated by Django 2.0.7 on 2019-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursekeywords',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
