# Generated by Django 2.0.7 on 2019-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobView', '0003_remove_coursedescription_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pneumonic', models.CharField(max_length=5)),
                ('course_name', models.TextField()),
                ('course_id', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('course_description', models.TextField()),
            ],
        ),
    ]
