# Generated by Django 2.0.7 on 2019-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobView', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_pneumonic', models.CharField(max_length=5)),
                ('course_id', models.IntegerField()),
                ('keyword', models.TextField()),
            ],
        ),
    ]
